# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ebaz4205.xdc

# Block Designs: bd/EBAZ4205/EBAZ4205.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EBAZ4205 || ORIG_REF_NAME==EBAZ4205} -quiet] -quiet

# IP: bd/EBAZ4205/ip/EBAZ4205_processing_system7_0_0/EBAZ4205_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EBAZ4205_processing_system7_0_0 || ORIG_REF_NAME==EBAZ4205_processing_system7_0_0} -quiet] -quiet

# IP: bd/EBAZ4205/ip/EBAZ4205_proc_sys_reset_0_0/EBAZ4205_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EBAZ4205_proc_sys_reset_0_0 || ORIG_REF_NAME==EBAZ4205_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/EBAZ4205/ip/EBAZ4205_xlconcat_0_0/EBAZ4205_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EBAZ4205_xlconcat_0_0 || ORIG_REF_NAME==EBAZ4205_xlconcat_0_0} -quiet] -quiet

# IP: bd/EBAZ4205/ip/EBAZ4205_xlconstant_0_0/EBAZ4205_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EBAZ4205_xlconstant_0_0 || ORIG_REF_NAME==EBAZ4205_xlconstant_0_0} -quiet] -quiet

# IP: bd/EBAZ4205/ip/EBAZ4205_xlconcat_0_1/EBAZ4205_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EBAZ4205_xlconcat_0_1 || ORIG_REF_NAME==EBAZ4205_xlconcat_0_1} -quiet] -quiet

# XDC: bd/EBAZ4205/EBAZ4205_ooc.xdc
