# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Dream/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-16736-DESKTOP-NE70URT/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/7020test/EBAZ4205/EBAZ4205.cache/wt [current_project]
set_property parent.project_path D:/7020test/EBAZ4205/EBAZ4205.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/7020test/EBAZ4205/EBAZ4205.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/hdl/EBAZ4205_wrapper.v
add_files D:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/EBAZ4205.bd
set_property used_in_implementation false [get_files -all d:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/ip/EBAZ4205_processing_system7_0_0/EBAZ4205_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/ip/EBAZ4205_proc_sys_reset_0_0/EBAZ4205_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/ip/EBAZ4205_proc_sys_reset_0_0/EBAZ4205_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/ip/EBAZ4205_proc_sys_reset_0_0/EBAZ4205_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/EBAZ4205_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/7020test/EBAZ4205/EBAZ4205.srcs/constrs_1/new/ebaz4205.xdc
set_property used_in_implementation false [get_files D:/7020test/EBAZ4205/EBAZ4205.srcs/constrs_1/new/ebaz4205.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top EBAZ4205_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef EBAZ4205_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file EBAZ4205_wrapper_utilization_synth.rpt -pb EBAZ4205_wrapper_utilization_synth.pb"
