# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/ip/EBAZ4205_processing_system7_0_0/EBAZ4205_processing_system7_0_0.xci
# IP: The module: 'EBAZ4205_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/ip/EBAZ4205_processing_system7_0_0/EBAZ4205_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EBAZ4205_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/ip/EBAZ4205_processing_system7_0_0/EBAZ4205_processing_system7_0_0.xci
# IP: The module: 'EBAZ4205_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/7020test/EBAZ4205/EBAZ4205.srcs/sources_1/bd/EBAZ4205/ip/EBAZ4205_processing_system7_0_0/EBAZ4205_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EBAZ4205_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
